#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95 # starts late
STOP=95 # reverse order - stops late; so if dependencies are down, it doesn't break 

service_data() {
        /usr/local/usr/bin/tuyadaemon -V
}                   
                
start_service() {   
	local enabled                    
	config_load "tuya"
	config_get productid config 'productid' ' '
	config_get deviceid config 'deviceid' ' '
	config_get devicesecret config 'devicesecret' ' '
	config_get enabled config 'enabled' 0

	if [ "$enabled" -eq 1 ]; then
		procd_open_instance          
		procd_set_param command /usr/local/usr/bin/tuyadaemon -p "$productid" -d "$deviceid" -s "$devicesecret"
		procd_set_param pidfile /var/run/tuyadaemon.pid                                                        
		procd_set_param file /etc/config/tuya  
		procd_close_instance                                                                                   
	fi                                                     
}                                                          
                                    
service_triggers() {
	procd_add_reload_trigger "tuya"
}                                            
                    
reload_service() {                           
	stop      
	start
}    
